# Generated by Django 3.2.23 on 2024-01-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('todo', models.BooleanField(default=False)),
                ('inprogress', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='media')),
                ('link', models.URLField(blank=True)),
                ('overdue', models.BooleanField(default=False)),
            ],
        ),
    ]
